kokoc_test/kokoc_test/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test.urls', namespace='test')),
    path('auth/', include('users.urls', namespace='users')),
    
]

kokoc_test/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('profile/', profile, name='profile'),
    path('list_users/', list_of_users, name='list')]

kokoc_test/users/models.py
from email.policy import default
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    balance = models.IntegerField(default=0)
    right_answers = models.IntegerField(default=0)

kokoc_test/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):

        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

kokoc_test/users/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model


from .forms import CreationForm


User = get_user_model()


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('test:index')
    template_name = 'users/signup.html'


@login_required
def profile(request):
    user = request.user
    context = {'user': user}
    return render(request, 'users/profile.html', context)


def list_of_users(request):
    users = User.objects.all()
    context = {'users': users }
    return render(request, 'users/list_users.html', context)

kokoc_test/templates/base.html
{% load static %}
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="ru">          
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" type="image" href="{% static 'img/fav/icon.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Контентище
      {% endblock %}
    </title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock content %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

kokoc_test/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
<p><span style="position: fixed;
    padding: 10px 10px 0px 10px;
    text-align: center;
    bottom: 0;
    width: 100%;
    /* Height of the footer*/
    height: 40px;">2023 KokocGroup</p>

kokoc_test/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: mediumslateblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'test:index' %}">
        <span style="color:white">KoKoC Group Tests</span>
      </a>
      {% if user.is_authenticated %}

      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link link-light" href="">{{ user.username | title }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'test:done_tests' %}">Пройденные тесты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="">Баланс: {{ user.balance }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:list' %}">Список пользователей</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:profile' %}">Профиль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>

kokoc_test/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

kokoc_test/templates/users/list_users.html
{% extends 'base.html' %}
{% block content %}
{% for user in users %}
<div class="container py-5">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
          <button >
                Пользователь:        {{ user }} <br/>
                Баланс пользователя: {{ user.balance }}
          </button>

      </li>
    </ul>
</div>
{% endfor %}

{% endblock content %}

kokoc_test/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

kokoc_test/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

kokoc_test/templates/users/profile.html
{% extends 'base.html' %}
{% block title %}Ваш профиль{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Профиль
      </div>
      <div class="card-body">
        <body>
          Имя пользователя: {{ user.username }} <br/>
          Пройдено тестов: {{ user.right_answers }}
        </body>
      </div>
    </div>
  </div> 
</div> 
{% endblock %}

kokoc_test/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}